version: "2"
plugins:
  # --
  # It chokes on our Regexp patterns.
  # I don't know why, but I should probably file
  #   a ticket to let them know.
  # --
  duplication:
    enabled: false
  rubocop:
    enabled: true
    config:
      file: .rubocop.yml
ratings:
  paths:
  - "spec/tests/**.rb"
  - "lib/**.rb"
