Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%q': '{}'
    '%Q': '{}'
    '%r': '!!'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'
AllCops:
  Exclude:
    - examples/**/*
    - node_modules/**/*
    - vendor/**/*
