language: ruby
cache: bundler
sudo: false

#

rvm:
  - &ruby1 2.3.0
  - &ruby2 2.2.4
  - &ruby3 2.1.8
  - &jruby jruby-9.1.2.0
  - &rhead ruby-head

#

matrix:
  fast_finish: true
  allow_failures:
    - rvm: *jruby
    - rvm: *rhead

#

notifications:
  email:
    recipients:
      - jordon@envygeeks.io

#

branches:
  only:
    - master

#

addons:
  code_climate:
    repo_token:
      secure: "\
        SprHjZdYxOWHXrnDLKu+tTLI/28dgNlHGH9pUF0NIouu5nhWVizoRt1xK19s+6Rct9h/b8\
        H9In1ExFom05IcXX4c1JGX1LlGbWRV/BHRwgys+MpWJCLfs8kBigufDdZBmyXubEj2KsjE\
        WICu+GMg+ZHP0nVTa/FkoF5iAfY6NiE=\
      "
