language: ruby
after_success: script/report
before_script: script/report before
script: script/test
sudo: false
cache:
  bundler: true
  directories:
  - vendor/bundle
  - node_modules
env:
  global:
    - secure: "\
        JR7KLpy0oRWS9QFAoUvxR+phVwpKLL2PLJ9FJcn1OoUPlfyeCcr22VjK/\
        fNsD6agXfkWOzDVLyfoOHxA9RwmWEhSMT2w7djxMW3ZRLVQKkdQXYkfYt\
        q5jrz1ZFOWLHQB53dg2/Aq0ZJAlK4DzHofeka5nEFS0NVHzxnlIVVPGI=\
      "
  matrix:
  - JEKYLL_VERSION="~> 3.5.0" SPROCKETS_VERSION="~> 3.3" TEST_TYPE=spec
  - JEKYLL_VERSION="~> 3.5.0" SPROCKETS_VERSION="~> 4.0.beta" TEST_TYPE=spec
  - JEKYLL_VERSION="~> 3.6.0" SPROCKETS_VERSION="~> 4.0.beta" TEST_TYPE=spec
  - JEKYLL_VERSION="~> 3.6.0" SPROCKETS_VERSION="~> 3.3" TEST_TYPE=spec
  - TEST_TYPE=lints
rvm:
- &ruby24 2.4
- &ruby23 2.3
- &ruby-head ruby-head
- &jruby jruby-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: *ruby-head
  - rvm: *jruby

notifications:
  email:
    recipients:
    - jordon@envygeeks.io
    on_success: change
    on_failure: change
branches:
  only:
  - master
